robot_2:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz
       
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      position_controller:
        type: position_controllers/JointGroupPositionController

  position_controller:
    ros__parameters:
      joints:
        - robot_2/joint_1
        - robot_2/joint_2
        - robot_2/joint_3
        - robot_2/joint_4
        - robot_2/joint_5
        - robot_2/joint_6
      
        - robot_2/Slider 22
        - robot_2/Slider 23

        - robot_2/slider_11

